#!/usr/bin/env python3
"""
Test script to verify PDF generation capabilities.
Run this script to test if WeasyPrint and Playwright are working properly.
"""

import sys
import os


def test_weasyprint():
    """Test WeasyPrint installation and functionality"""
    print("Testing WeasyPrint...")
    try:
        from weasyprint import HTML, CSS
        from weasyprint.text.fonts import FontConfiguration

        # Create a simple test HTML
        test_html = """
        <!DOCTYPE html>
        <html>
        <head>
            <title>Test PDF</title>
        </head>
        <body>
            <h1>Test PDF Generation</h1>
            <p>This is a test PDF generated by WeasyPrint.</p>
        </body>
        </html>
        """

        # Generate PDF
        font_config = FontConfiguration()
        pdf_bytes = HTML(string=test_html).write_pdf(
            stylesheets=[CSS(string="body { font-family: Arial, sans-serif; }")],
            font_config=font_config,
        )

        print("✓ WeasyPrint is working correctly")
        print(f"✓ Generated PDF size: {len(pdf_bytes)} bytes")
        return True

    except ImportError as e:
        print(f"✗ WeasyPrint not available: {e}")
        return False
    except Exception as e:
        print(f"✗ WeasyPrint error: {e}")
        return False


def test_playwright():
    """Test Playwright installation and functionality"""
    print("\nTesting Playwright...")
    try:
        from playwright.sync_api import sync_playwright

        # Test basic import
        print("✓ Playwright imported successfully")

        # Test browser launch (this might fail in some environments)
        try:
            with sync_playwright() as p:
                browser = p.chromium.launch(headless=True)
                page = browser.new_page()
                page.set_content("<html><body><h1>Test</h1></body></html>")
                pdf_bytes = page.pdf()
                browser.close()

                print("✓ Playwright is working correctly")
                print(f"✓ Generated PDF size: {len(pdf_bytes)} bytes")
                return True
        except Exception as e:
            print(f"✗ Playwright browser launch failed: {e}")
            return False

    except ImportError as e:
        print(f"✗ Playwright not available: {e}")
        return False
    except Exception as e:
        print(f"✗ Playwright error: {e}")
        return False


def main():
    print("Testing PDF generation capabilities...")
    print("=" * 50)

    weasyprint_ok = test_weasyprint()
    playwright_ok = test_playwright()

    print("\n" + "=" * 50)
    print("Test Results:")
    print(f"WeasyPrint: {'✓ Working' if weasyprint_ok else '✗ Not working'}")
    print(f"Playwright: {'✓ Working' if playwright_ok else '✗ Not working'}")

    if weasyprint_ok or playwright_ok:
        print("\n✓ PDF generation is available!")
        if weasyprint_ok:
            print("  - WeasyPrint will be used as the primary PDF generator")
        elif playwright_ok:
            print("  - Playwright will be used as the primary PDF generator")
    else:
        print(
            "\n✗ No PDF generation available. The system will fall back to HTML files."
        )
        print("  - Users will receive HTML files instead of PDFs")
        print("  - Users can print HTML files to PDF using their browser")


if __name__ == "__main__":
    main()
