"""
Django settings for bitbio project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import pymysql

# Initialize PyMySQL to work with Django
pymysql.install_as_MySQLdb()

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-z45x*8#9292((t56%@$ohm5isgf29@p$24wx0q2&k7(ao!g-^w"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

# ALLOWED_HOSTS setting
allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "").strip()
if allowed_hosts_env:
    ALLOWED_HOSTS = [
        host.strip() for host in allowed_hosts_env.split(",") if host.strip()
    ]
else:
    ALLOWED_HOSTS = [
        "member.bit.bio",
        "bitbiohost.uksouth.cloudapp.azure.com",
        "rdg.capture.dev.workplaceservicing.co.uk",
        "fs.capture.dev.workplaceservicing.co.uk",
        "localhost",
        "127.0.0.1",
    ]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app_users",
    "calculator",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "app_users.middleware.ApprovalStatusMiddleware",
    "bitbio.admin_middleware.AdminAccessMiddleware",
]

ROOT_URLCONF = "bitbio.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "bitbio" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.csrf",
            ],
        },
    },
]

WSGI_APPLICATION = "bitbio.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.mysql"),
        "NAME": os.getenv("DB_NAME", "bit_bio_django"),
        "USER": os.getenv("DB_USER", "root"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'",
            "charset": "utf8mb4",
            "autocommit": True,
            "use_unicode": True,
        },
    }
}

# MySQL configuration (commented out for now)
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "bit_bio_django",
#         "USER": "root",
#         "PASSWORD": "",
#         "HOST": "localhost",
#         "PORT": "3306",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.getenv("LANGUAGE_CODE", "en-us")

TIME_ZONE = os.getenv("TIME_ZONE", "UTC")

USE_I18N = os.getenv("USE_I18N", "True").lower() == "true"

USE_TZ = os.getenv("USE_TZ", "True").lower() == "true"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.getenv("STATIC_URL", "/static/")
STATICFILES_DIRS = [
    BASE_DIR / "bitbio" / "static",
    BASE_DIR / "calculator" / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (uploaded content)
MEDIA_URL = os.getenv("MEDIA_URL", "/media/")
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = "app_users.User"

# Custom authentication backends
AUTHENTICATION_BACKENDS = [
    "app_users.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Login URL for @login_required decorator
LOGIN_URL = os.getenv("LOGIN_URL", "/")

# Admin Security Settings
ADMIN_SITE_HEADER = os.getenv("ADMIN_SITE_HEADER", "🧬 BitBio Administration")
ADMIN_SITE_TITLE = os.getenv("ADMIN_SITE_TITLE", "BitBio Admin Portal")
ADMIN_INDEX_TITLE = os.getenv("ADMIN_INDEX_TITLE", "Welcome to BitBio Administration")

# Security settings for admin access
ADMIN_LOGIN_REDIRECT_URL = os.getenv("ADMIN_LOGIN_REDIRECT_URL", "/admin/")
ADMIN_LOGOUT_REDIRECT_URL = os.getenv("ADMIN_LOGOUT_REDIRECT_URL", "/")

# Session security for admin users
SESSION_COOKIE_SECURE = (
    os.getenv("SESSION_COOKIE_SECURE", "False").lower() == "true"
)  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = int(
    os.getenv("SESSION_COOKIE_AGE", "3600")
)  # 1 hour session timeout
SESSION_EXPIRE_AT_BROWSER_CLOSE = (
    os.getenv("SESSION_EXPIRE_AT_BROWSER_CLOSE", "True").lower() == "true"
)

# CSRF protection
CSRF_COOKIE_SECURE = (
    os.getenv("CSRF_COOKIE_SECURE", "False").lower() == "true"
)  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for AJAX requests
CSRF_COOKIE_SAMESITE = (
    "Lax"  # Prevent CSRF attacks while allowing some cross-site usage
)
CSRF_USE_SESSIONS = False  # Use cookies instead of session for CSRF tokens
CSRF_COOKIE_AGE = 31449600  # 1 year in seconds (52 weeks * 7 days * 24 hours * 60 minutes * 60 seconds)
CSRF_TRUSTED_ORIGINS = [
    "https://member.bit.bio",
    "https://bitbiohost.uksouth.cloudapp.azure.com",
    "http://bitbiohost.uksouth.cloudapp.azure.com",
    "https://fs.capture.dev.workplaceservicing.co.uk",
    "https://rdg.capture.dev.workplaceservicing.co.uk",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Cache configuration - using database cache instead of Redis
# Optimized for production server with 8GB RAM
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "cache_table",
        "KEY_PREFIX": "bitbio",
        "TIMEOUT": int(
            os.getenv("CACHE_TIMEOUT", "600")
        ),  # 10 minutes default for production
        "OPTIONS": {
            "MAX_ENTRIES": 10000,  # Increased for better performance
            "CULL_FREQUENCY": 3,  # Remove 1/3 of entries when MAX_ENTRIES reached
        },
    }
}

# Logging configuration
# Ensure logs directory exists
logs_dir = BASE_DIR / "logs"
logs_dir.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
        "performance": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": logs_dir / "django.log",
            "formatter": "verbose",
            "maxBytes": 50 * 1024 * 1024,  # 50MB
            "backupCount": 5,
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": logs_dir / "errors.log",
            "formatter": "verbose",
            "maxBytes": 20 * 1024 * 1024,  # 20MB
            "backupCount": 3,
        },
        "performance_file": {
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": logs_dir / "performance.log",
            "formatter": "performance",
            "maxBytes": 10 * 1024 * 1024,  # 10MB
            "backupCount": 2,
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["file", "console", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["performance_file"],
            "level": "WARNING",
            "propagate": False,
        },
        "gunicorn.error": {
            "handlers": ["error_file"],
            "level": "ERROR",
            "propagate": False,
        },
        "bitbio": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Performance monitoring settings for production
# Database connection pool optimization for your server
DATABASES["default"]["CONN_MAX_AGE"] = 3600  # Keep connections alive for 1 hour
DATABASES["default"]["OPTIONS"].update(
    {
        "connect_timeout": 20,
        "read_timeout": 30,
        "write_timeout": 30,
    }
)

# Security headers for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
