# Generated by Django 5.2.4 on 2025-08-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whitelisted_domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of whitelisted domains for auto-approval",
                    ),
                ),
                (
                    "blocklisted_domains",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of blocklisted domains that are rejected",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
                "db_table": "domains",
            },
        ),
    ]
