# Generated by Django 5.1.3 on 2025-10-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopify_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shopify_customer_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
