# Generated by Django 5.1.3 on 2025-10-02 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_user_shopify_access_token_user_shopify_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shopify_access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shopify_customer_id',
        ),
        migrations.CreateModel(
            name='ShopifyUserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_customer_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('shopify_access_token', models.TextField(blank=True, null=True)),
                ('shopify_first_name', models.CharField(blank=True, max_length=100)),
                ('shopify_last_name', models.CharField(blank=True, max_length=100)),
                ('shopify_email', models.EmailField(blank=True, max_length=254)),
                ('shopify_verified_email', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopify User Session',
                'verbose_name_plural': 'Shopify User Sessions',
                'db_table': 'shopify_user_session',
                'indexes': [models.Index(fields=['shopify_customer_id'], name='shopify_customer_id_idx'), models.Index(fields=['last_sync_at'], name='shopify_last_sync_idx')],
            },
        ),
    ]
