# Generated by Django 5.2.7 on 2025-10-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_alter_shopifyusersession_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifyusersession',
            name='user',
        ),
    ]
