# Generated by Django 5.1.3 on 2025-08-19 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CellType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=100, unique=True)),
                (
                    "seeding_density",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "products",
                "ordering": ["product_name"],
            },
        ),
        migrations.CreateModel(
            name="CultureVessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_format", models.CharField(max_length=255)),
                (
                    "surface_area_cm2",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "media_volume_per_well_ml",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "culture_vessels",
                "ordering": ["plate_format"],
            },
        ),
        migrations.CreateModel(
            name="CalculationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suspension_volume",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("count1", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "count2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "count3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("viability1", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "viability2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "viability3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("cell_type", models.CharField(max_length=255)),
                (
                    "seeding_density",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("culture_vessel", models.CharField(max_length=255)),
                ("surface_area", models.DecimalField(decimal_places=4, max_digits=10)),
                ("media_volume", models.DecimalField(decimal_places=4, max_digits=10)),
                ("num_wells", models.IntegerField()),
                ("buffer", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Calculation Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
