# Generated by Django 5.2.4 on 2025-09-01 08:04

from django.db import migrations


def populate_culture_vessels(apps, schema_editor):
    CultureVessel = apps.get_model("calculator", "CultureVessel")

    culture_vessels_data = [
        {
            "plate_format": "96-well plate",
            "surface_area_cm2": 0.32,
            "media_volume_per_well_ml": 0.1,
        },
        {
            "plate_format": "6-well plate",
            "surface_area_cm2": 9.6,
            "media_volume_per_well_ml": 2.5,
        },
        {
            "plate_format": "12-well plate",
            "surface_area_cm2": 3.5,
            "media_volume_per_well_ml": 1,
        },
        {
            "plate_format": "24-well plate",
            "surface_area_cm2": 1.9,
            "media_volume_per_well_ml": 0.5,
        },
        {
            "plate_format": "48-well plate",
            "surface_area_cm2": 1.1,
            "media_volume_per_well_ml": 0.25,
        },
        {
            "plate_format": "384-well plate",
            "surface_area_cm2": 0.056,
            "media_volume_per_well_ml": 0.03,
        },
        {"plate_format": "Other", "surface_area_cm2": 0, "media_volume_per_well_ml": 0},
    ]

    for vessel_data in culture_vessels_data:
        CultureVessel.objects.get_or_create(
            plate_format=vessel_data["plate_format"],
            defaults={
                "surface_area_cm2": vessel_data["surface_area_cm2"],
                "media_volume_per_well_ml": vessel_data["media_volume_per_well_ml"],
            },
        )


def reverse_populate_culture_vessels(apps, schema_editor):
    CultureVessel = apps.get_model("calculator", "CultureVessel")
    CultureVessel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            populate_culture_vessels, reverse_populate_culture_vessels
        ),
    ]
