# Generated by Django 5.2.4 on 2025-09-01 08:04

from django.db import migrations


def populate_products(apps, schema_editor):
    CellType = apps.get_model("calculator", "CellType")

    products_data = [
        {"product_name": "ioAstrocytes", "sku": "ioEA1093", "seeding_density": 30000},
        {
            "product_name": "ioGABAergic Neurons",
            "sku": "io1003",
            "seeding_density": 150000,
        },
        {
            "product_name": "ioGABAergic Neurons APP V717I/V717I",
            "sku": "io1081",
            "seeding_density": 150000,
        },
        {
            "product_name": "ioGABAergic Neurons APP V717I/WT",
            "sku": "io1085",
            "seeding_density": 150000,
        },
        {
            "product_name": "ioGlutamatergic Neurons",
            "sku": "io1001",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons APP KM670/671NL / KM670/671NL",
            "sku": "io1059",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons APP KM670/671NL/WT",
            "sku": "io1061",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons APP V717I/V717I",
            "sku": "io1063",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons APP V717I/WT",
            "sku": "io1067",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons GBA null/R159W",
            "sku": "io1007",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons HTT 50CAG/WT",
            "sku": "ioEA1004",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons MAPT N279K/N279K",
            "sku": "io1014",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons MAPT N279K/WT",
            "sku": "io1009",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons MAPT P301S/P301S",
            "sku": "io1008",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons MAPT P301S/WT",
            "sku": "io1015",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons PINK1 Q456X/Q456X",
            "sku": "io1076",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons PINK1 Q456X/WT",
            "sku": "io1079",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons PRKN R275W/R275W",
            "sku": "io1020",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons PRKN R275W/WT",
            "sku": "io1013",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons PSEN1 M146L/M146L",
            "sku": "io1069",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons PSEN1 M146L/WT",
            "sku": "io1072",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons SNCA A53T/A53T",
            "sku": "io1088",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons SNCA A53T/WT",
            "sku": "io6005",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons TDP-43 M337V/M337V",
            "sku": "ioEA1005",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioGlutamatergic Neurons TDP-43 M337V/WT",
            "sku": "ioEA1006",
            "seeding_density": 30000,
        },
        {
            "product_name": "CRISPRa-Ready ioGlutamatergic Neurons",
            "sku": "io1099",
            "seeding_density": 30000,
        },
        {
            "product_name": "CRISPRi-Ready ioGlutamatergic Neurons",
            "sku": "io1098",
            "seeding_density": 30000,
        },
        {
            "product_name": "CRISPRko-Ready ioGlutamatergic Neurons",
            "sku": "io1090",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioMicroglia Female",
            "sku": "io1029",
            "seeding_density": 39500,
        },
        {"product_name": "ioMicroglia Male", "sku": "io1021", "seeding_density": 39500},
        {
            "product_name": "CRISPRko-Ready ioMicroglia Male",
            "sku": "io1094",
            "seeding_density": 39500,
        },
        {
            "product_name": "GFP ioMicroglia Male",
            "sku": "io1096",
            "seeding_density": 39500,
        },
        {
            "product_name": "ioMicroglia APOE 4/3 C112R/WT",
            "sku": "io1033",
            "seeding_density": 39500,
        },
        {
            "product_name": "ioMicroglia APOE 4/4 C112R/C112R",
            "sku": "io1032",
            "seeding_density": 39500,
        },
        {
            "product_name": "ioMicroglia TREM2 R47H/R47H",
            "sku": "io1035",
            "seeding_density": 39500,
        },
        {
            "product_name": "ioMicroglia TREM2 R47H/WT",
            "sku": "io1038",
            "seeding_density": 39500,
        },
        {"product_name": "ioMotor Neurons", "sku": "io1027", "seeding_density": 30000},
        {
            "product_name": "ioMotor Neurons FUS P525L/P525L",
            "sku": "io1052",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioMotor Neurons FUS P525L/WT",
            "sku": "io1055",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioMotor Neurons SOD-1 G93A/G93A",
            "sku": "io1041",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioMotor Neurons SOD-1 G93A/WT",
            "sku": "io1042",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioMotor Neurons TDP-43 M337V/M337V",
            "sku": "io1046",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioMotor Neurons TDP-43 M337V/WT",
            "sku": "io1050",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioMotor Neurons TDP-43 A382T/WT",
            "sku": "io6019",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioMotor Neurons TDP-43 N352S/WT",
            "sku": "io6017",
            "seeding_density": 30000,
        },
        {
            "product_name": "ioOligodendrocyte-like cells",
            "sku": "io1028",
            "seeding_density": 27000,
        },
        {
            "product_name": "ioSensory Neurons",
            "sku": "io1024",
            "seeding_density": 60000,
        },
        {
            "product_name": "ioSkeletal Myocytes",
            "sku": "io1002",
            "seeding_density": 100000,
        },
        {
            "product_name": "ioSkeletal Myocytes DMD Exon 44 Deletion",
            "sku": "io1018",
            "seeding_density": 100000,
        },
        {
            "product_name": "ioSkeletal Myocytes DMD Exon 52 Deletion",
            "sku": "io1019",
            "seeding_density": 100000,
        },
    ]

    for product_data in products_data:
        CellType.objects.get_or_create(
            sku=product_data["sku"],
            defaults={
                "product_name": product_data["product_name"],
                "seeding_density": product_data["seeding_density"],
            },
        )


def reverse_populate_products(apps, schema_editor):
    CellType = apps.get_model("calculator", "CellType")
    CellType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0002_auto_20250901_1304"),
    ]

    operations = [
        migrations.RunPython(populate_products, reverse_populate_products),
    ]
